# Generated by Django 2.2.1 on 2019-08-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xadmin.Log')),
                ('operatorname', models.CharField(max_length=30, verbose_name='操作模块')),
            ],
            bases=('xadmin.log',),
        ),
    ]
