# Generated by Django 2.2.1 on 2019-09-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objecttable', models.CharField(max_length=30, null=True, verbose_name='操作表格')),
                ('objectID', models.IntegerField(null=True, verbose_name='操作对象')),
                ('actiontime', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('action', models.IntegerField(choices=[(1, '添加'), (2, '删除'), (3, '更改')], null=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('message', models.CharField(max_length=30, null=True, verbose_name='详细信息')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
