# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productionManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeTips', models.CharField(max_length=999, null=True, verbose_name='入库备注')),
                ('storeTime', models.DateField(auto_now_add=True, verbose_name='入库时间')),
                ('amount', models.FloatField(verbose_name='入库总数量')),
                ('unit', models.CharField(max_length=20, verbose_name='数量单位')),
                ('storeHouse', models.CharField(max_length=20, verbose_name='存储仓库')),
                ('restAmount', models.FloatField(verbose_name='剩余数量')),
                ('isNormal', models.BooleanField(default='True', verbose_name='是否正常')),
                ('hashWords', models.CharField(max_length=256, verbose_name='hash文字')),
                ('storingPeriod', models.IntegerField(default=0, verbose_name='存储时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionManagement.HarvestInfo', verbose_name='批次')),
            ],
            options={
                'verbose_name': '入库信息',
                'verbose_name_plural': '入库信息',
            },
        ),
    ]
