# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProductionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawProductionName', models.CharField(max_length=10, verbose_name='源产品名称')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.CompanyInfo', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '源产品信息',
                'verbose_name_plural': '源产品信息',
            },
        ),
        migrations.CreateModel(
            name='RawProductionManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualityControlMeasure', models.CharField(default='', max_length=20, verbose_name='措施简称')),
                ('measureDescription', models.CharField(default='', max_length=500, verbose_name='措施详情')),
                ('orderNumber', models.IntegerField(default=0, verbose_name='序号')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('flag', models.BooleanField(default=False, verbose_name='是否追溯')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='隶属公司')),
                ('rawProductionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawProduction.RawProductionInfo', verbose_name='品种')),
            ],
            options={
                'verbose_name': '源产品质量管理措施',
                'verbose_name_plural': '源产品质量管理措施',
            },
        ),
    ]
