# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=20, verbose_name='公司任务名称')),
                ('taskDescription', models.CharField(max_length=999, verbose_name='公司任务描述')),
                ('deadline', models.DateField(verbose_name='截止日期')),
            ],
            options={
                'verbose_name': '公司任务',
                'verbose_name_plural': '公司任务',
            },
        ),
        migrations.CreateModel(
            name='CompanyTaskReceiveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivingTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '任务领取信息',
                'verbose_name_plural': '任务领取信息',
            },
        ),
        migrations.CreateModel(
            name='PersonTaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=20, verbose_name='私人任务')),
                ('taskDescription', models.CharField(max_length=200, verbose_name='私人任务描述')),
                ('isRead', models.BooleanField(verbose_name='是否已读')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='发布公司')),
            ],
            options={
                'verbose_name': '私人任务',
                'verbose_name_plural': '私人任务',
            },
        ),
    ]
