# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontaskinfo',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务负责人'),
        ),
        migrations.AddField(
            model_name='companytaskreceiveinfo',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='接受公司'),
        ),
        migrations.AddField(
            model_name='companytaskreceiveinfo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManagement.CompanyTaskInfo', verbose_name='公司任务'),
        ),
    ]
