# Generated by Django 2.2.1 on 2019-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identityClass',
            field=models.IntegerField(choices=[('0', '维护员'), ('1', '系统管理员'), ('2', '系统操作员'), ('3', '操作员')], null=True, verbose_name='权限等级'),
        ),
    ]
