# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('rawProduction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockinfo',
            name='rawProduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rawProduction.RawProductionInfo', verbose_name='种植源产品编号'),
        ),
    ]
