# Generated by Django 2.2.1 on 2019-09-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0002_auto_20190928_1700'),
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='unityID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.UnityInfo', verbose_name='联盟编号'),
        ),
        migrations.AlterField(
            model_name='blockinfo',
            name='rawProduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rawProduction.RawProductionInfo', verbose_name='种植源产品编号'),
        ),
    ]
