# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costName', models.CharField(max_length=99, null=True, verbose_name='花销名称')),
                ('costType', models.CharField(choices=[('food', '餐饮'), ('purchase', '采购'), ('waterCharge', '水费'), ('electricCharge', '电费'), ('salary', '工资'), ('rest', '其他')], max_length=10, verbose_name='花销种类')),
                ('costTips', models.CharField(max_length=999, null=True, verbose_name='花销备注')),
                ('costAmount', models.IntegerField(verbose_name='花销金额')),
                ('costTime', models.DateField(verbose_name='花销时间')),
                ('isNormal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('hashWords', models.CharField(max_length=256, verbose_name='hash')),
            ],
            options={
                'verbose_name': '支出信息',
                'verbose_name_plural': '支出信息',
            },
        ),
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeName', models.CharField(max_length=99, null=True, verbose_name='收入名称')),
                ('incomeType', models.CharField(choices=[('sale', '销售'), ('subsidy', '补贴'), ('rest', '其他')], max_length=10, verbose_name='收入种类')),
                ('incomeTips', models.CharField(max_length=999, null=True, verbose_name='收入备注')),
                ('incomeAmount', models.IntegerField(verbose_name='收入金额')),
                ('incomeTime', models.DateField(verbose_name='收入时间')),
                ('isNormal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('hashWords', models.CharField(max_length=256, verbose_name='hash')),
                ('incomeCompany', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.CompanyInfo', verbose_name='收入公司')),
            ],
            options={
                'verbose_name': '收入信息',
                'verbose_name_plural': '收入信息',
            },
        ),
    ]
