# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costDescription', models.CharField(max_length=999, null=True, verbose_name='描述')),
                ('date', models.DateField(null=True, verbose_name='使用时间')),
                ('isNormal', models.BooleanField(default=True, verbose_name='状态')),
                ('hashWords', models.CharField(max_length=256, verbose_name='hash')),
                ('timeStrap', models.BinaryField(null=True, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '投入品交易',
                'verbose_name_plural': '投入品交易',
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20, verbose_name='投入品名称')),
                ('itemDescription', models.CharField(max_length=999, null=True, verbose_name='投入品描述')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='所属公司编号')),
            ],
            options={
                'verbose_name': '投入品种类',
                'verbose_name_plural': '投入品种类',
            },
        ),
    ]
