# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemStore', '0001_initial'),
        ('productionManagement', '0001_initial'),
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcostinfo',
            name='costBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionManagement.SowInfo', verbose_name='使用批次'),
        ),
        migrations.AddField(
            model_name='itemcostinfo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itemStore.ItemInfo', verbose_name='种类'),
        ),
        migrations.AddField(
            model_name='itemcostinfo',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.MemberInfo', verbose_name='负责员工'),
        ),
    ]
