# Generated by Django 2.2.1 on 2019-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unityinfo',
            options={'verbose_name': '联盟信息'},
        ),
        migrations.AddField(
            model_name='unityinfo',
            name='unityProfile',
            field=models.CharField(max_length=30, null=True, verbose_name='联盟简介'),
        ),
    ]
