# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleName', models.CharField(max_length=20, verbose_name='销售名称')),
                ('buyer', models.CharField(max_length=100, verbose_name='购买方')),
                ('amount', models.FloatField(default=0, verbose_name='售出数量')),
                ('saleTips', models.CharField(max_length=999, null=True, verbose_name='销售备注')),
                ('saleTime', models.DateField(verbose_name='售出时间')),
                ('isNormal', models.BooleanField(default=True, verbose_name='数据状态是否正常')),
                ('hashWords', models.CharField(max_length=256, verbose_name='hash数据')),
                ('TimeStrap', models.BinaryField(default='', verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '销售信息',
                'verbose_name_plural': '销售信息',
            },
        ),
    ]
