# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saleManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productionStore', '0002_auto_20190521_1425'),
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinfo',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='saleBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionStore.StoreInfo', verbose_name='销售批次'),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='saleMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.MemberInfo', verbose_name='负责人'),
        ),
    ]
