# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productionManagement', '0001_initial'),
        ('rawProduction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_blockinfo_rawproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowinfo',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='sowinfo',
            name='sowingBlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.BlockInfo', verbose_name='播种地块'),
        ),
        migrations.AddField(
            model_name='sowinfo',
            name='sowingCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='播种公司'),
        ),
        migrations.AddField(
            model_name='sowinfo',
            name='sowingMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.MemberInfo', verbose_name='播种人'),
        ),
        migrations.AddField(
            model_name='sowinfo',
            name='sowingProduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawProduction.RawProductionInfo', verbose_name='播种产品'),
        ),
        migrations.AddField(
            model_name='measureconfirminginfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='measureconfirminginfo',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawProduction.RawProductionManagement', verbose_name='环节'),
        ),
        migrations.AddField(
            model_name='measureconfirminginfo',
            name='rawProduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawProduction.RawProductionInfo', verbose_name='品种'),
        ),
        migrations.AddField(
            model_name='measureconfirminginfo',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录者'),
        ),
        migrations.AddField(
            model_name='measureconfirminginfo',
            name='sowingBatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionManagement.SowInfo', verbose_name='播种批次'),
        ),
        migrations.AddField(
            model_name='harvestinfo',
            name='harvestBatch',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='productionManagement.SowInfo', verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='harvestinfo',
            name='harvestCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='收获公司'),
        ),
        migrations.AddField(
            model_name='harvestinfo',
            name='harvestMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.MemberInfo', verbose_name='收获人'),
        ),
        migrations.AddField(
            model_name='harvestinfo',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
    ]
