# Generated by Django 2.2.1 on 2019-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='动态标题')),
                ('description', models.CharField(max_length=200, verbose_name='动态内容')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '系统动态',
                'verbose_name_plural': '系统动态',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='SysRegulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regName', models.CharField(max_length=20, verbose_name='规章制度')),
                ('regDescription', models.CharField(max_length=200, verbose_name='制度详情')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '规章制度',
                'verbose_name_plural': '规章制度',
            },
        ),
    ]
